server {
    listen 80;
    listen [::]:80;

    server_name vitalisempreendimentos.com.br www.vitalisempreendimentos.com.br;

    root /var/www/vitalis;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
